variables:
  PYTHON_VERSION: "3.14"
  BASE_LAYER: bookworm-slim
  # GitLab CI creates a separate mountpoint for the build directory,
  # so we need to copy instead of using hard links.
  UV_LINK_MODE: copy

check:
  image: ghcr.io/astral-sh/uv:python$PYTHON_VERSION-$BASE_LAYER
  script:
    - uv tool run ruff check --no-fix

publish:
  stage: deploy
  image:
    name: ghcr.io/astral-sh/uv:python$PYTHON_VERSION-$BASE_LAYER
  script:
    - uv build
    - uv publish --index kof --username gitlab --password $PACKAGE_REGISTRY_PASSWORD
    - uv publish --index testpypi --username __token__ --password $TESTPYPI_TOKEN
  rules:
    - if: $CI_COMMIT_TAG

